server:
  port: 8081

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zxy_blog_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: elwgelwg




# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


