server:
  port: 8888

spring:
  thymeleaf:
    cache: false
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
#    useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
#    characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: LF@0827

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


